export const INIT_QUESTIONS = "INIT_QUESTIONS";
export const INIT_USERS = "INIT_USERS";
export const SET_AUTH_USER = "SET_AUTH_USER";
export const ADD_ANSWER_TO_USER = "ADD_ANSWER_TO_USER";
export const ADD_ANSWER_TO_QUESTIONS = "ADD_ANSWER_TO_QUESTIONS";
export const ADD_QUESTION_TO_USER = "ADD_QUESTION_TO_USER";
export const ADD_QUESTION_TO_QUESTIONS = "ADD_QUESTION_TO_QUESTIONS";
